import type { GameConfig } from "../types/game.types.js";

const MIN_BET_ETH = "0.000115";

export const GAMES_REGISTRY: GameConfig[] = [
  {
    id: "coin-flip",
    name: "Coin Flip",
    description: "Heads or tails? Simplest onchain bet.",
    path: "/games/coin-flip",
    contractName: "CoinFlipGame",
    minBetEth: MIN_BET_ETH,
    maxBetEth: "0.0005",
    houseEdgePercent: 5,
    maxMultiplier: 2,
    active: true,
    chains: ["baseMainnet"],
    requiresWebSocket: false,
    tags: ["simple", "fast"]
  },
  {
    id: "dice",
    name: "Dice",
    description: "Guess 1-6. Right guess pays 6x gross before edge.",
    path: "/games/dice",
    contractName: "DiceGame",
    minBetEth: MIN_BET_ETH,
    maxBetEth: "0.0005",
    houseEdgePercent: 5,
    maxMultiplier: 6,
    active: true,
    chains: ["baseMainnet"],
    requiresWebSocket: false,
    tags: ["simple", "fast"]
  },
  {
    id: "crash",
    name: "Crash",
    description: "Multiplier rises; cash out before it crashes.",
    path: "/games/crash",
    contractName: "CrashGame",
    minBetEth: MIN_BET_ETH,
    maxBetEth: "0.0005",
    houseEdgePercent: 5,
    maxMultiplier: 10,
    active: true,
    chains: ["baseMainnet"],
    requiresWebSocket: true,
    tags: ["popular", "realtime"]
  },
  {
    id: "mines",
    name: "Mines",
    description: "Reveal gems, avoid bombs. Multiplier grows.",
    path: "/games/mines",
    contractName: "MinesGame",
    minBetEth: MIN_BET_ETH,
    maxBetEth: "0.0005",
    houseEdgePercent: 5,
    maxMultiplier: 20,
    active: true,
    chains: ["baseMainnet"],
    requiresWebSocket: false,
    tags: ["strategy"]
  },
  {
    id: "hilo",
    name: "Hi-Lo",
    description: "Predict next card. Chain wins to multiply.",
    path: "/games/hilo",
    contractName: "HiLoGame",
    minBetEth: MIN_BET_ETH,
    maxBetEth: "0.0005",
    houseEdgePercent: 5,
    maxMultiplier: 8,
    active: true,
    chains: ["baseMainnet"],
    requiresWebSocket: false,
    tags: ["strategy", "fast"]
  },
  {
    id: "over-under",
    name: "Over / Under",
    description: "Pick a threshold and roll over or under 1-100.",
    path: "/games/over-under",
    contractName: "OverUnderGame",
    minBetEth: MIN_BET_ETH,
    maxBetEth: "0.0005",
    houseEdgePercent: 5,
    maxMultiplier: 20,
    active: true,
    chains: ["baseMainnet"],
    requiresWebSocket: false,
    tags: ["simple", "odds"]
  },
  {
    id: "limbo",
    name: "Limbo",
    description: "Set a target multiplier. Higher target, lower chance.",
    path: "/games/limbo",
    contractName: "LimboGame",
    minBetEth: MIN_BET_ETH,
    maxBetEth: "0.0005",
    houseEdgePercent: 5,
    maxMultiplier: 20,
    active: true,
    chains: ["baseMainnet"],
    requiresWebSocket: false,
    tags: ["fast", "risk"]
  },
  {
    id: "wheel",
    name: "Wheel",
    description: "Spin a 16-segment wheel with low, medium, or high risk.",
    path: "/games/wheel",
    contractName: "WheelGame",
    minBetEth: MIN_BET_ETH,
    maxBetEth: "0.0005",
    houseEdgePercent: 5,
    maxMultiplier: 8,
    active: true,
    chains: ["baseMainnet"],
    requiresWebSocket: false,
    tags: ["arcade", "spin"]
  },
  {
    id: "plinko-lite",
    name: "Plinko Lite",
    description: "Drop through 8 rows and land in a multiplier slot.",
    path: "/games/plinko-lite",
    contractName: "PlinkoLiteGame",
    minBetEth: MIN_BET_ETH,
    maxBetEth: "0.0005",
    houseEdgePercent: 5,
    maxMultiplier: 25,
    active: true,
    chains: ["baseMainnet"],
    requiresWebSocket: false,
    tags: ["arcade", "drop"]
  },
  {
    id: "color-pick",
    name: "Color Pick",
    description: "Choose one of four colors. VRF reveals the winning color.",
    path: "/games/color-pick",
    contractName: "ColorPickGame",
    minBetEth: MIN_BET_ETH,
    maxBetEth: "0.0005",
    houseEdgePercent: 5,
    maxMultiplier: 4,
    active: true,
    chains: ["baseMainnet"],
    requiresWebSocket: false,
    tags: ["casual", "fast"]
  },
  {
    id: "treasure-chest",
    name: "Treasure Chest",
    description: "Pick a chest. One of nine hides the prize.",
    path: "/games/treasure-chest",
    contractName: "TreasureChestGame",
    minBetEth: MIN_BET_ETH,
    maxBetEth: "0.0005",
    houseEdgePercent: 5,
    maxMultiplier: 9,
    active: true,
    chains: ["baseMainnet"],
    requiresWebSocket: false,
    tags: ["casual", "jackpot"]
  },
  {
    id: "lucky-seven",
    name: "Lucky Seven",
    description: "Roll two dice and bet under, exactly, or over seven.",
    path: "/games/lucky-seven",
    contractName: "LuckySevenGame",
    minBetEth: MIN_BET_ETH,
    maxBetEth: "0.0005",
    houseEdgePercent: 5,
    maxMultiplier: 6,
    active: true,
    chains: ["baseMainnet"],
    requiresWebSocket: false,
    tags: ["dice", "casual"]
  },
  {
    id: "roulette-lite",
    name: "Roulette Lite",
    description: "Pick a number, color, or range on a 12-slot wheel.",
    path: "/games/roulette-lite",
    contractName: "RouletteLiteGame",
    minBetEth: MIN_BET_ETH,
    maxBetEth: "0.0005",
    houseEdgePercent: 5,
    maxMultiplier: 12,
    active: true,
    chains: ["baseMainnet"],
    requiresWebSocket: false,
    tags: ["arcade", "odds"]
  },
  {
    id: "scratch-card",
    name: "Scratch Card",
    description: "Reveal a VRF-backed prize tier with up to 30x payout.",
    path: "/games/scratch-card",
    contractName: "ScratchCardGame",
    minBetEth: MIN_BET_ETH,
    maxBetEth: "0.0005",
    houseEdgePercent: 5,
    maxMultiplier: 30,
    active: true,
    chains: ["baseMainnet"],
    requiresWebSocket: false,
    tags: ["casual", "jackpot"]
  },
  {
    id: "rock-paper-scissors",
    name: "Rock Paper Scissors",
    description: "Choose a move. VRF picks the house move without ties.",
    path: "/games/rock-paper-scissors",
    contractName: "RockPaperScissorsGame",
    minBetEth: MIN_BET_ETH,
    maxBetEth: "0.0005",
    houseEdgePercent: 5,
    maxMultiplier: 2,
    active: true,
    chains: ["baseMainnet"],
    requiresWebSocket: false,
    tags: ["simple", "fast"]
  },
  {
    id: "slots",
    name: "Slots",
    description: "Spin three VRF reels. Pairs and triples pay.",
    path: "/games/slots",
    contractName: "SlotsGame",
    minBetEth: MIN_BET_ETH,
    maxBetEth: "0.0005",
    houseEdgePercent: 5,
    maxMultiplier: 25,
    active: true,
    chains: ["baseMainnet"],
    requiresWebSocket: false,
    tags: ["arcade", "jackpot"]
  }
];

export const getGame = (id: string) => GAMES_REGISTRY.find((game) => game.id === id);

export const getActiveGames = (networkKey: string) =>
  GAMES_REGISTRY.filter((game) => game.active && game.chains.includes(networkKey));
